dist: trusty
sudo: required

env:
  - PACKER_VERSION=1.2.2

install:
  - curl -Os https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
  - curl -Os https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS
  - curl -Os https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS.sig
  - gpg --import hashicorp.asc
  - gpg --verify packer_${PACKER_VERSION}_SHA256SUMS.sig packer_${PACKER_VERSION}_SHA256SUMS
  - shasum -a 256 -c packer_${PACKER_VERSION}_SHA256SUMS 2> /dev/null | grep packer_${PACKER_VERSION}_linux_amd64.zip | grep OK
  - sudo unzip -o packer_${PACKER_VERSION}_linux_amd64.zip -d /usr/local/bin
  - sudo chmod 755 /usr/local/bin/packer

script:
  - packer validate -syntax-only centos/centos.json
  - packer validate -syntax-only debian/debian.json
  - packer validate -syntax-only fedora/fedora.json
  - packer validate -syntax-only ubuntu/ubuntu.json
